version: '3'

services:
  myDB:
    image: postgres:15.3
    container_name: soa-database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=adminadmin
      - POSTGRES_DB=heycap
    volumes:
      - ./postgres:/var/lib/postgresql/data
